# This Jupyter Notebook covers all the requested topics:

1) Python Basics including loops, functions, lists, and dictionaries

2) NumPy arrays and vectorized operations

3) Matrix multiplication and broadcasting

# Python Basics

In [3]:
print("I am Your Friend, Saud!")

x = 1  
y = 69
name = "Python"  

sum_result = x + 5
product = x * y
division = x / 2
modulus = x % 3
exponent = x ** 2

print(f"Sum: {sum_result}, Product: {product}, Division: {division}, Modulus: {modulus}, Exponent: {exponent}")

I am Your Friend, Saud!
Sum: 6, Product: 69, Division: 0.5, Modulus: 1, Exponent: 1


# Loops

For Loop with range

In [7]:
for i in range(5):
    print(f"Count: {i}")

Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


For loop with list

In [10]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(f"I like {fruit}")

I like apple
I like banana
I like cherry


While loop

In [13]:
counter = 0
while counter < 3:
    print(f"Counter: {counter}")
    counter += 1

Counter: 0
Counter: 1
Counter: 2


Nested loop

In [16]:
for i in range(3):
    for j in range(2):
        print(f"i={i}, j={j}")

i=0, j=0
i=0, j=1
i=1, j=0
i=1, j=1
i=2, j=0
i=2, j=1


For-else

In [19]:
for i in range(3):
    print(i)
else:
    print("Loop completed without break")

0
1
2
Loop completed without break


While-else

In [22]:
num = 0
while num < 3:
    print(f"Number: {num}")
    num += 1
else:
    print("While loop completed")

Number: 0
Number: 1
Number: 2
While loop completed


# Functions 

Simple function

In [26]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Saud"))

Hello, Saud!


Function with default parameter

In [29]:
def power(base, exponent=2):
    return base ** exponent

print(f"Power(3): {power(3)}")
print(f"Power(3, 3): {power(3, 3)}")

Power(3): 9
Power(3, 3): 27


*args for variable number of arguments

In [32]:
def sum_all(*numbers):
    return sum(numbers)

print(f"Sum: {sum_all(66, 67, 67, 67)}")

Sum: 267


**kwargs for keyword arguments

In [35]:
def person_info(**details):
    for key, value in details.items():
        print(f"{key}: {value}")

person_info(name="Saud", age=20, city="RIYADH")

name: Saud
age: 20
city: RIYADH


Lambda function

In [38]:
square = lambda x: x ** 2
print(f"Square of 5: {square(5)}")

# Using lambda with map
numbers = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x ** 2, numbers))
print(f"Squared numbers: {squared}")

Square of 5: 25
Squared numbers: [1, 4, 9, 16, 25]


Recursive function

In [41]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

print(f"Factorial of 67: {factorial(67)}")

Factorial of 67: 36471110918188685288249859096605464427167635314049524593701628500267962436943872000000000000000


Generator function

In [44]:
def count_up_to(max):
    count = 1
    while count <= max:
        yield count
        count += 1

counter = count_up_to(67)
print(f"Generator values: {list(counter)}")

Generator values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67]


#  Lists

In [47]:
# Create a sample list
my_list = [1, 2, 3, 4, 5]
print(f"Original list: {my_list}")

# 1. append() - Add element at the end
my_list.append(6)
print(f"1. After append(6): {my_list}")

# 2. extend() - Add multiple elements
my_list.extend([7, 8])
print(f"2. After extend([7, 8]): {my_list}")

# 3. insert() - Insert element at specific position
my_list.insert(2, 99)
print(f"3. After insert(2, 99): {my_list}")

# 4. remove() - Remove first occurrence of value
my_list.remove(99)
print(f"4. After remove(99): {my_list}")

# 5. pop() - Remove and return element at index
popped = my_list.pop(3)
print(f"5. After pop(3): {my_list}, Popped: {popped}")


Original list: [1, 2, 3, 4, 5]
1. After append(6): [1, 2, 3, 4, 5, 6]
2. After extend([7, 8]): [1, 2, 3, 4, 5, 6, 7, 8]
3. After insert(2, 99): [1, 2, 99, 3, 4, 5, 6, 7, 8]
4. After remove(99): [1, 2, 3, 4, 5, 6, 7, 8]
5. After pop(3): [1, 2, 3, 5, 6, 7, 8], Popped: 4


In [49]:
# 6. index() - Find index of element
index_of_5 = my_list.index(5)
print(f"6. Index of 5: {index_of_5}")

# 7. count() - Count occurrences
my_list.append(5)
count_of_5 = my_list.count(5)
print(f"7. Count of 5: {count_of_5}")

# 8. sort() - Sort list in place
my_list.sort()
print(f"8. After sort(): {my_list}")

# 9. reverse() - Reverse list in place
my_list.reverse()
print(f"9. After reverse(): {my_list}")

# 10. copy() - Create shallow copy
list_copy = my_list.copy()
print(f"10. Copy of list: {list_copy}")

6. Index of 5: 3
7. Count of 5: 2
8. After sort(): [1, 2, 3, 5, 5, 6, 7, 8]
9. After reverse(): [8, 7, 6, 5, 5, 3, 2, 1]
10. Copy of list: [8, 7, 6, 5, 5, 3, 2, 1]


In [51]:
# 11. clear() - Remove all elements
my_list.clear()
print(f"11. After clear(): {my_list}")

# Restore list
my_list = list_copy.copy()

# 12. len() - Get length
print(f"12. Length of list: {len(my_list)}")

# 13. max() and min()
print(f"13. Max: {max(my_list)}, Min: {min(my_list)}")

# 14. sum() - Sum of all elements
print(f"14. Sum of list: {sum(my_list)}")

11. After clear(): []
12. Length of list: 8
13. Max: 8, Min: 1
14. Sum of list: 37


# Dictionaries

In [54]:
print("=== DICTIONARY BASICS ===")
student = {
    "name": "John",
    "age": 20,
    "major": "Computer Science",
    "grades": {"math": 90, "physics": 85, "chemistry": 88}
}
print(f"Student dictionary: {student}")

=== DICTIONARY BASICS ===
Student dictionary: {'name': 'John', 'age': 20, 'major': 'Computer Science', 'grades': {'math': 90, 'physics': 85, 'chemistry': 88}}


In [56]:
print("\n=== LIST TO DICTIONARY ===")
keys = ['a', 'b', 'c']
values = [1, 2, 3]

# Method 1: Using zip()
dict_from_list = dict(zip(keys, values))
print(f"Dictionary from zip: {dict_from_list}")

# Method 2: Dictionary comprehension
list_of_tuples = [('x', 10), ('y', 20), ('z', 30)]
dict_from_tuples = {k: v for k, v in list_of_tuples}
print(f"Dictionary from comprehension: {dict_from_tuples}")



=== LIST TO DICTIONARY ===
Dictionary from zip: {'a': 1, 'b': 2, 'c': 3}
Dictionary from comprehension: {'x': 10, 'y': 20, 'z': 30}


In [58]:
print("\n=== DICTIONARY TO LIST ===")
# Keys to list
keys_list = list(student.keys())
print(f"Keys as list: {keys_list}")

# Values to list
values_list = list(student.values())
print(f"Values as list: {values_list}")

# Items to list
items_list = list(student.items())
print(f"Items as list of tuples: {items_list}")


=== DICTIONARY TO LIST ===
Keys as list: ['name', 'age', 'major', 'grades']
Values as list: ['John', 20, 'Computer Science', {'math': 90, 'physics': 85, 'chemistry': 88}]
Items as list of tuples: [('name', 'John'), ('age', 20), ('major', 'Computer Science'), ('grades', {'math': 90, 'physics': 85, 'chemistry': 88})]


In [60]:
print("\n=== TUPLES WITH DICTIONARIES ===")
# Tuples as dictionary keys
coordinate_dict = {
    (0, 0): "Origin",
    (1, 2): "Point A",
    (3, 4): "Point B"
}
print(f"Dictionary with tuple keys: {coordinate_dict}")
print(f"Value at (1, 2): {coordinate_dict[(1, 2)]}")


=== TUPLES WITH DICTIONARIES ===
Dictionary with tuple keys: {(0, 0): 'Origin', (1, 2): 'Point A', (3, 4): 'Point B'}
Value at (1, 2): Point A


In [62]:
print("\n=== DICTIONARY METHODS ===")
# Dictionary methods
print(f"get('name'): {student.get('name')}")
print(f"get('nonexistent', 'default'): {student.get('nonexistent', 'default')}")

# Update dictionary
student.update({"year": "Junior", "gpa": 3.8})
print(f"After update: {student}")

# Pop item
popped_item = student.pop("age")
print(f"After pop('age'): {student}, Popped: {popped_item}")

# Pop last item
last_item = student.popitem()
print(f"After popitem(): {student}, Last item: {last_item}")

# Setdefault
student.setdefault("status", "Active")
print(f"After setdefault: {student}")


=== DICTIONARY METHODS ===
get('name'): John
get('nonexistent', 'default'): default
After update: {'name': 'John', 'age': 20, 'major': 'Computer Science', 'grades': {'math': 90, 'physics': 85, 'chemistry': 88}, 'year': 'Junior', 'gpa': 3.8}
After pop('age'): {'name': 'John', 'major': 'Computer Science', 'grades': {'math': 90, 'physics': 85, 'chemistry': 88}, 'year': 'Junior', 'gpa': 3.8}, Popped: 20
After popitem(): {'name': 'John', 'major': 'Computer Science', 'grades': {'math': 90, 'physics': 85, 'chemistry': 88}, 'year': 'Junior'}, Last item: ('gpa', 3.8)
After setdefault: {'name': 'John', 'major': 'Computer Science', 'grades': {'math': 90, 'physics': 85, 'chemistry': 88}, 'year': 'Junior', 'status': 'Active'}


In [64]:
print("\n=== DICTIONARY COMPREHENSION ===")
# Dictionary comprehension
squares = {x: x**2 for x in range(1, 6)}
print(f"Squares dictionary: {squares}")

even_squares = {x: x**2 for x in range(1, 11) if x % 2 == 0}
print(f"Even squares: {even_squares}")


=== DICTIONARY COMPREHENSION ===
Squares dictionary: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25}
Even squares: {2: 4, 4: 16, 6: 36, 8: 64, 10: 100}


# NumPy

In [67]:
import numpy as np

In [69]:
print("=== NUMPY ARRAYS ===")
# Creating arrays
arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1}")
print(f"Type: {type(arr1)}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr2d}")
print(f"Shape: {arr2d.shape}")

=== NUMPY ARRAYS ===
1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data type: int32

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [71]:
# Special arrays
zeros_arr = np.zeros((3, 3))
print(f"\nZeros array:\n{zeros_arr}")

ones_arr = np.ones((2, 4))
print(f"\nOnes array:\n{ones_arr}")

identity_arr = np.eye(3)
print(f"\nIdentity matrix:\n{identity_arr}")

range_arr = np.arange(0, 10, 2)
print(f"\nArray from arange: {range_arr}")

linspace_arr = np.linspace(0, 1, 5)
print(f"\nLinspace array: {linspace_arr}")


Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array from arange: [0 2 4 6 8]

Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [73]:
print("\n=== VECTORIZED OPERATIONS ===")
# Vectorized operations
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"Array a: {a}")
print(f"Array b: {b}")

# Element-wise operations
print(f"\nElement-wise addition: {a + b}")
print(f"Element-wise subtraction: {a - b}")
print(f"Element-wise multiplication: {a * b}")
print(f"Element-wise division: {a / b}")
print(f"Element-wise exponent: {a ** 2}")
print(f"Element-wise square root: {np.sqrt(a)}")

# Comparison operations
print(f"\nElement-wise comparison (a > 2): {a > 2}")
print(f"Element-wise comparison (a == b): {a == b}")

# Mathematical functions
print(f"\nSine of a: {np.sin(a)}")
print(f"Exponential of a: {np.exp(a)}")
print(f"Logarithm of a: {np.log(a)}")

# Aggregate operations
print(f"\nSum of a: {np.sum(a)}")
print(f"Mean of a: {np.mean(a)}")
print(f"Standard deviation of a: {np.std(a)}")
print(f"Minimum of a: {np.min(a)}")
print(f"Maximum of a: {np.max(a)}")
print(f"Index of max value: {np.argmax(a)}")

# Array indexing and slicing
print(f"\nArray indexing and slicing:")
print(f"a[2]: {a[2]}")
print(f"a[1:3]: {a[1:3]}")
print(f"a[::-1]: {a[::-1]}")


=== VECTORIZED OPERATIONS ===
Array a: [1 2 3 4]
Array b: [5 6 7 8]

Element-wise addition: [ 6  8 10 12]
Element-wise subtraction: [-4 -4 -4 -4]
Element-wise multiplication: [ 5 12 21 32]
Element-wise division: [0.2        0.33333333 0.42857143 0.5       ]
Element-wise exponent: [ 1  4  9 16]
Element-wise square root: [1.         1.41421356 1.73205081 2.        ]

Element-wise comparison (a > 2): [False False  True  True]
Element-wise comparison (a == b): [False False False False]

Sine of a: [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Exponential of a: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Logarithm of a: [0.         0.69314718 1.09861229 1.38629436]

Sum of a: 10
Mean of a: 2.5
Standard deviation of a: 1.118033988749895
Minimum of a: 1
Maximum of a: 4
Index of max value: 3

Array indexing and slicing:
a[2]: 3
a[1:3]: [2 3]
a[::-1]: [4 3 2 1]


# Matrix Operations and Broadcasting

In [76]:
print("=== MATRIX MULTIPLICATION ===")
# Creating matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Matrix A:\n{A}")
print(f"\nMatrix B:\n{B}")
print(f"\nMatrix C:\n{C}")

=== MATRIX MULTIPLICATION ===
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix C:
[[1 2 3]
 [4 5 6]]


In [78]:
# Element-wise multiplication
print(f"\nElement-wise multiplication (A * B):\n{A * B}")

# Matrix multiplication (@ operator)
print(f"\nMatrix multiplication (A @ B):\n{A @ B}")

# Matrix multiplication (np.dot)
print(f"\nMatrix multiplication (np.dot(A, B)):\n{np.dot(A, B)}")

# Matrix multiplication (np.matmul)
print(f"\nMatrix multiplication (np.matmul(A, B)):\n{np.matmul(A, B)}")


Element-wise multiplication (A * B):
[[ 5 12]
 [21 32]]

Matrix multiplication (A @ B):
[[19 22]
 [43 50]]

Matrix multiplication (np.dot(A, B)):
[[19 22]
 [43 50]]

Matrix multiplication (np.matmul(A, B)):
[[19 22]
 [43 50]]


In [80]:
# Matrix with vector
vector = np.array([1, 2])
print(f"\nVector: {vector}")
print(f"Matrix-vector multiplication (A @ vector):\n{A @ vector}")

# Matrix properties
print(f"\nMatrix A:")
print(f"Shape: {A.shape}")
print(f"Determinant: {np.linalg.det(A)}")
print(f"Transpose:\n{A.T}")
print(f"Inverse:\n{np.linalg.inv(A)}")


Vector: [1 2]
Matrix-vector multiplication (A @ vector):
[ 5 11]

Matrix A:
Shape: (2, 2)
Determinant: -2.0000000000000004
Transpose:
[[1 3]
 [2 4]]
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [82]:
print("\n=== BROADCASTING ===")
# Broadcasting examples
print("Broadcasting allows operations between arrays of different shapes")

# Example 1: Adding scalar to array
scalar = 10
arr = np.array([1, 2, 3])
result = arr + scalar
print(f"\nArray: {arr}")
print(f"Scalar: {scalar}")
print(f"Array + scalar: {result}")

# Example 2: Adding 1D array to 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector1d = np.array([10, 20, 30])
result1 = matrix + vector1d
print(f"\nMatrix:\n{matrix}")
print(f"\n1D Vector: {vector1d}")
print(f"\nMatrix + 1D Vector (broadcasted):\n{result1}")


=== BROADCASTING ===
Broadcasting allows operations between arrays of different shapes

Array: [1 2 3]
Scalar: 10
Array + scalar: [11 12 13]

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Vector: [10 20 30]

Matrix + 1D Vector (broadcasted):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [84]:
print("\n=== PRACTICAL BROADCASTING EXAMPLES ===")
# Normalizing rows of a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original matrix:\n{matrix}")

# Subtract row means
row_means = matrix.mean(axis=1, keepdims=True)
normalized = matrix - row_means
print(f"\nRow means (keepdims=True):\n{row_means}")
print(f"\nMatrix - Row means:\n{normalized}")

# Outer product using broadcasting
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
outer_product = a[:, np.newaxis] * b
print(f"\nVector a: {a}")
print(f"Vector b: {b}")
print(f"Outer product (a.T * b):\n{outer_product}")

# Pairwise distances
points = np.array([[1, 2], [3, 4], [5, 6]])
print(f"\nPoints:\n{points}")
print(f"Points[:, np.newaxis, :] shape: {points[:, np.newaxis, :].shape}")
print(f"Points[np.newaxis, :, :] shape: {points[np.newaxis, :, :].shape}")


=== PRACTICAL BROADCASTING EXAMPLES ===
Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Row means (keepdims=True):
[[2.]
 [5.]
 [8.]]

Matrix - Row means:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

Vector a: [1 2 3]
Vector b: [4 5 6]
Outer product (a.T * b):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Points:
[[1 2]
 [3 4]
 [5 6]]
Points[:, np.newaxis, :] shape: (3, 1, 2)
Points[np.newaxis, :, :] shape: (1, 3, 2)
